name: memories
services:
  db:
    container_name: memories-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=memories-user
      - POSTGRES_PASSWORD=memories-password
      - POSTGRES_DB=memories-db
    ports:
      - "1111:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d